apiVersion: apps/v1
kind: Deployment
metadata:
  name: wtapp
  labels:
    app: wtapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wtapp
  template:
    metadata:
      labels:
        app: wtapp
    spec:
      containers:
      - name: wtapp
        image: ors09/wtapp2:latest
        envFrom:
          - configMapRef:
             name: config-app
          - secretRef:
             name: app-sercrets
        